// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBn6HwlfRjI0IqvM5qlwbn6eMe7LyDe9Y',
    authDomain: 'create-social-4d07d.firebaseapp.com',
    databaseURL: 'https://create-social-4d07d-default-rtdb.firebaseio.com',
    projectId: 'create-social-4d07d',
    storageBucket: 'gs://create-social-4d07d.appspot.com/',
    messagingSenderId: "114856754788",
    appId: '1:114856754788:web:8fe0d2cd4c6f3088eb6971',
    measurementId: "G-EJC821L8PQ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsWS5akxO587bNqvur_YYW5E969J_X1EY',
    appId: '1:114856754788:android:1a348d52601e370eeb6971',
    messagingSenderId: '114856754788',
    projectId: 'create-social-4d07d',
    storageBucket: 'gs://create-social-4d07d.appspot.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC95oS7N_kfcVEkXMiupJK1qKnCkpWwQLs',
    appId: '1:114856754788:ios:14233662da31cf3ceb6971',
    messagingSenderId: '114856754788',
    projectId: 'create-social-4d07d',
    storageBucket: 'gs://create-social-4d07d.appspot.com/',
    iosClientId:
        '684296137056-mmdkqjsh229l1et0bc805j8pq3v58q5k.apps.googleusercontent.com',
    iosBundleId: 'com.creationdriven.createSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4bDNR3EqBkYyR4VRcpRHbStuX-kL6nS8',
    appId: '1:684296137056:ios:fc9c257a018a6ec10a1605',
    messagingSenderId: '114856754788',
    projectId: 'create-social-4d07d',
    storageBucket: 'gs://create-social-4d07d.appspot.com/',
    iosClientId:
        '684296137056-mmdkqjsh229l1et0bc805j8pq3v58q5k.apps.googleusercontent.com',
    iosBundleId: 'com.creationdriven.createSocial',
  );
}
